// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4WDq6oXH4YGUhRSWMizszjlCWrYoiyA',
    appId: '1:117081426110:web:dbc3d9181915dd147c76ef',
    messagingSenderId: '117081426110',
    projectId: 'victorfonghu-9b3',
    authDomain: 'victorfonghu-9b3.firebaseapp.com',
    storageBucket: 'victorfonghu-9b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG4lKI2GPePR3DihljyrYEWxsXhB8_DKY',
    appId: '1:117081426110:android:e5bbc00bb85396cf7c76ef',
    messagingSenderId: '117081426110',
    projectId: 'victorfonghu-9b3',
    storageBucket: 'victorfonghu-9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA663U_hF0h3PRqlKxaa-A3-IFCJ6bXCi8',
    appId: '1:117081426110:ios:380a20bf8f89e76d7c76ef',
    messagingSenderId: '117081426110',
    projectId: 'victorfonghu-9b3',
    storageBucket: 'victorfonghu-9b3.appspot.com',
    iosBundleId: 'com.example.firebaseVictordonghu3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA663U_hF0h3PRqlKxaa-A3-IFCJ6bXCi8',
    appId: '1:117081426110:ios:380a20bf8f89e76d7c76ef',
    messagingSenderId: '117081426110',
    projectId: 'victorfonghu-9b3',
    storageBucket: 'victorfonghu-9b3.appspot.com',
    iosBundleId: 'com.example.firebaseVictordonghu3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt4WDq6oXH4YGUhRSWMizszjlCWrYoiyA',
    appId: '1:117081426110:web:bd4b839ae8c9ee6a7c76ef',
    messagingSenderId: '117081426110',
    projectId: 'victorfonghu-9b3',
    authDomain: 'victorfonghu-9b3.firebaseapp.com',
    storageBucket: 'victorfonghu-9b3.appspot.com',
  );
}
